#!/usr/bin/env bash
# make nginx listen on port 80
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
kill -s HUP $( cat /run/nginx.pid  )
