#!/usr/bin/env bash
# This Script displays To infinity and beyond indefinitely
# and various messages based on signal recieved

echo "$$" > /var/run/holbertonscript.pid
trap "{ echo 'I hate the kill command'; remove_exit }" SIGTERM
trap "{ echo 'Y U no love me?!'; }" SIGINT
trap remove_exit SIGQUIT

function remove_exit () {
    rm -f /var/run/holbertonscript.pid
    exit 1
}

while :
do
    echo "To infinity and beyond"
done
