#!/usr/bin/env bash
# This Script displays To infinity and beyond indefinitely
# and various messages based on signal recieved

echo "$$" > /var/run/holbertonscript.pid
trap "echo 'Y U no love me?!'" SIGINT
trap remove_exit 1 SIGTERM
trap remove_exit SIGQUIT

function remove_exit {
    if [ "$1" == 1 ]
    then
       echo 'I hate the kill command'
    fi
    rm -f /var/run/holbertonscript.pid
    exit 1
}

while :
do
    echo "To infinity and beyond"
    sleep 2
done
