#!/usr/bin/env bash
# This script prints "bad luck" 4th iteration, "good luck" on the 8th iteration, and "Holberton School" for other iterations
n=1

while [ $n -le 20 ]
do
    echo $n
    if [ $n -eq 4 ]
    then
        echo "bad luck from China"
    elif [ $n -eq 9 ]
    then
        echo "bad luck from Japan"
    elif [ $n -eq 17 ]
    then
        echo "bad luck from Italy"
    fi
    n=$(( n + 1 ))
done
