#!/usr/bin/env bash
# this script will alter the hosts file

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
cp -f ~/hosts.new /etc/hosts
