#!/usr/bin/env bash
# makes apache2 web server listen on port 8080

echo "Listen 8080" >> /etc/apache2/ports.conf
sed -i "s/<VirtualHost \*:80>/<VirtualHost \*:80 \*:8080>/" /etc/apache2/sites-enabled/000-default.conf
service apache2 restart
