#!/usr/bin/env bash
# runs nginx as nginx
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
